### ISSUE TITLE
`RefMutContainer` could be dropped when its owner still exists 

### ISSUE THREAD

**Issue by jopemachine** [lablup/rraft-py#36]
The below code shows `RefMutContainer` can drop when its Owner variable still exists.  

```py
>>> import rraft
>>> s = rraft.MemStorage()
>>> s.initial_state().initialized()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
rraft.DestroyedRefUsedError: Cannot use a destroyed object's reference!
```

So, users should save the intermediate variable somewhere.

(For example, See `v2` in https://github.com/lablup/rraft-py/blob/1566964/harness/tests/test_raft.py#L4255)

It would be great if users doesn't need to save these variables.

I'm uncertain if it could be possible.

**Comment by rapsealk** [comment]
```python
import rraft

class MemStorageWrapper:
    def __init__(self):
        self._storage = rraft.MemStorage()
        self._initial_state = None

    def initial_state(self):
        if self._initial_state is None:
            self._initial_state = self._storage.initial_state()
        return self._initial_state
```

**Comment by jopemachine** [comment]
I found that the mere presence of method chaining does not guarantee that the error will be reproduced.

```
Python 3.11.3 (main, May 11 2023, 10:45:37) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rraft
>>> snapshot = rraft.Snapshot.default()
>>> snapshot.get_metadata().set_index(0)
>>> 
```

**Comment by jopemachine** [comment]
Oh, I found `initial_state` of mem_storage returns Owner type instead of Reference type.

This seems the cause of this weird bug 😅

Because when a method returns Owner type, it should be dropped in python when its reference count is zero.

**Comment by jopemachine** [comment]
I think it's a very part to miss, but it's not a bug, so I will close this issue.
